version: '3.8'

services:
  db:
    image: postgres:15
    container_name: quiz-db
    restart: always
    environment:
      POSTGRES_DB: quiz_backend_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5433:5432"
    volumes:
      - quiz-data:/var/lib/postgresql/data

  app:
    build: .
    container_name: quiz-backend
    restart: always
    depends_on:
      - db
    ports:
      - "8081:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/quiz_backend_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: admin
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
      SPRING_JACKSON_DESERIALIZATION_FAIL_ON_UNKNOWN_PROPERTIES: "false"

volumes:
  quiz-data:
